### ISSUE TITLE
Add exception case for image group IDs that only contain 4 digits

### ISSUE THREAD

**Issue by TBRC-Travis** [buda-base/volume-manifest-builder#42]
For example, consider image group ID **W28882-4784**

According to Elie:

> if an image group ID (such as I4784) in the database, the
> code that constructs its S3 path has one condition:
> - if the image group is I + 4 digits, it only uses the 4 digits, not the I
> - else it uses the full image group ID
> So in that case it looks for W28882-4784

v_m_b will need an exceptional case made for any "I + 4 digits" image group IDs so that it searches for the appropriate image group folder on disk.

**Comment by jimk-bdrc** [comment]
I'm not in favor of this change.  v-m-b has tried to depend on eXist and BUDA to canonically define image groups.
If BUDA and eXist require this kind of gyration, they should implement APIs that deliver their desired results to their clients.


> Hi Elie,I didn't get this email directly, for some reason, but all I can say is that this is bullshit.
v-m-b tried to depend on BUDA to get image group names, and, for some reason, BUDA couldn't or  wouldn't implement, or withdrewthis API (after I had spent quite a bit of time implementing the reader for it)
http://purl.bdrc.io/query/table/Work_ImgList?R_RES=bdr:{_work}' \
 '&format=csv&profile=simple&pageSize=500'
and 
http://purl.bdrc.io/query/Work_ImgList?R_RES=bdr:{_work}' \
 '&format=csv&profile=simple&pageSize=500'I remember you mentioned there was some big hoo-hah about this query altogether, (it doesn't seem to return anything) and so  I reverted to using an eXist query,https://www.tbrc.org/public?module=work&query=work-igs&args=
And now you're telling me that those eXist queries have exceptional cases too, so why do I even bother using such a corrupt database?
Rather than propagating a hack like the work you've described, might I request that BUDA provide the equivalent 
of 
https://www.tbrc.org/public?module=work&query=work-igs&args=
and post-process the output according to its own needs?
If that breaks tbrc.org, then I don't have a problem with that.

**Comment by eroux** [comment]
Hi Jim, I don't think your answer welcomes a constructive disussion and I won't answer it. If AO is wanting to disrupt things for no reason, I think Jann should be involved, not me. I don't have anything to do with this.

**Comment by jimk-bdrc** [comment]
It turns out we had already implemented it, so I'm just going to write a separate bug report for this case.

**Comment by JannTibetan** [comment]
Hi guys,

This is not the tone I’d like to set at the office. Please come to me first when a strong disagreement is brewing. I’d like to be involved in finding an early resolution to issues such as this one. 

Jann

**Comment by jimk-bdrc** [comment]
AO agreed to close this, and address the issue in #43
